### ISSUE TITLE
Compiled Phar Pls Daddy

### ISSUE THREAD

**Issue by Johnsonk79** [thebigsmileXD/InstantRespawn#1]
^ thx daddy dan!

**Comment by inxomnyaa** [comment]
...poggit does not work for me currently

**Comment by Johnsonk79** [comment]
aw :<

**Comment by Johnsonk79** [comment]
can daddy dan release it on GitHub then?

**Comment by inxomnyaa** [comment]
Ask @SOF3 to fix outdated jquery issue on Poggit and then i can. Right now i dont have the tools to inject virions into phars.

**Comment by SOF3** [comment]
What's wrong? There's no problem with my browser in incognito.
![image](https://user-images.githubusercontent.com/19623715/81136784-1db94d80-8f8f-11ea-8211-a73624168dec.png)

**Comment by inxomnyaa** [comment]
It appears fixed now. The old jQuery 3.2.1 version was not accessible the last weeks. Release building now

**Comment by Johnsonk79** [comment]
Hmmm somehow it can't be downloaded from poggit, the download button currently says N/A

**Comment by SOF3** [comment]
> Hmmm somehow it can't be downloaded from poggit, the download button currently says N/A

See #4

**Comment by inxomnyaa** [comment]
PR by @SOF3 Fixed it, phar now should build
