### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lolmanz0** [thebigsmileXD/InstantRespawn#2]
"Could not pass event 'pocketmine\event\player\PlayerMoveEvent' to 'InstantRespawn v0.3.2': Call to undefined method pocketmine\level\Level::getSpawn() on thebigsmileXD\InstantRespawn\Main

**Comment by thebigsmileXD** [comment]
The plugin is deprecated and no longer maintained

**Comment by lolmanz0** [comment]
:(
