### ISSUE TITLE
Class "CortexPE\Command\BaseCommand' not found

### ISSUE THREAD

**Issue by ghost** [thebigsmileXD/InstantRespawn#5]
When I attempt to load the plugin, the following error message appears:

Error: "Class 'CortexPE\Commando\BaseCommand' not found" (EXCEPTION) in "plugins/InstantRespawn-master/src/xenialdan/InstantRespawn/Command" at line 14

I have tried installing the Command plugin and put it in my plugins folder, but it is still unable to load.

**Comment by inxomnyaa** [comment]
Duplicate of #2 #3
